package com.identity.domain;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_name
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_time
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_address
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_transFrom
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventTransfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_transTo
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventTransto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_transValue
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String eventTransvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.blockNum
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String blocknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.transferHash
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    private String transferhash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_name
     *
     * @return the value of event.event_name
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_name
     *
     * @param eventName the value for event.event_name
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_time
     *
     * @return the value of event.event_time
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_time
     *
     * @param eventTime the value for event.event_time
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventTime(String eventTime) {
        this.eventTime = eventTime == null ? null : eventTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_address
     *
     * @return the value of event.event_address
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventAddress() {
        return eventAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_address
     *
     * @param eventAddress the value for event.event_address
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventAddress(String eventAddress) {
        this.eventAddress = eventAddress == null ? null : eventAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_transFrom
     *
     * @return the value of event.event_transFrom
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventTransfrom() {
        return eventTransfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_transFrom
     *
     * @param eventTransfrom the value for event.event_transFrom
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventTransfrom(String eventTransfrom) {
        this.eventTransfrom = eventTransfrom == null ? null : eventTransfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_transTo
     *
     * @return the value of event.event_transTo
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventTransto() {
        return eventTransto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_transTo
     *
     * @param eventTransto the value for event.event_transTo
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventTransto(String eventTransto) {
        this.eventTransto = eventTransto == null ? null : eventTransto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_transValue
     *
     * @return the value of event.event_transValue
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getEventTransvalue() {
        return eventTransvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_transValue
     *
     * @param eventTransvalue the value for event.event_transValue
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setEventTransvalue(String eventTransvalue) {
        this.eventTransvalue = eventTransvalue == null ? null : eventTransvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.blockNum
     *
     * @return the value of event.blockNum
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getBlocknum() {
        return blocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.blockNum
     *
     * @param blocknum the value for event.blockNum
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setBlocknum(String blocknum) {
        this.blocknum = blocknum == null ? null : blocknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.transferHash
     *
     * @return the value of event.transferHash
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public String getTransferhash() {
        return transferhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.transferHash
     *
     * @param transferhash the value for event.transferHash
     *
     * @mbg.generated Thu May 09 00:55:14 CST 2019
     */
    public void setTransferhash(String transferhash) {
        this.transferhash = transferhash == null ? null : transferhash.trim();
    }
}