package com.identity.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.publicKey
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String publickey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.time
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wallet
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    private String wallet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.publicKey
     *
     * @return the value of user.publicKey
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getPublickey() {
        return publickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.publicKey
     *
     * @param publickey the value for user.publicKey
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setPublickey(String publickey) {
        this.publickey = publickey == null ? null : publickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.time
     *
     * @return the value of user.time
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.time
     *
     * @param time the value for user.time
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wallet
     *
     * @return the value of user.wallet
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public String getWallet() {
        return wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wallet
     *
     * @param wallet the value for user.wallet
     *
     * @mbg.generated Wed May 08 16:08:30 CST 2019
     */
    public void setWallet(String wallet) {
        this.wallet = wallet == null ? null : wallet.trim();
    }
}